# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Project/GameOfLife/prj/project_microblaze/project_microblaze.cache/wt [current_project]
set_property parent.project_path C:/Project/GameOfLife/prj/project_microblaze/project_microblaze.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/Project/GameOfLife/ip [current_project]
set_property ip_output_repo c:/Project/GameOfLife/prj/project_microblaze/project_microblaze.cache/ip [current_project]
set_property ip_cache_permissions disable [current_project]
read_ip -quiet C:/Project/GameOfLife/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xci
set_property used_in_implementation false [get_files -all c:/Project/GameOfLife/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Project/GameOfLife/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Project/GameOfLife/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_ooc.xdc]
set_property is_locked true [get_files C:/Project/GameOfLife/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_clk_wiz_1_0 -part xc7z020clg484-1 -mode out_of_context

rename_ref -prefix_all design_1_clk_wiz_1_0_

write_checkpoint -force -noxdef design_1_clk_wiz_1_0.dcp

catch { report_utilization -file design_1_clk_wiz_1_0_utilization_synth.rpt -pb design_1_clk_wiz_1_0_utilization_synth.pb }

if { [catch {
  file copy -force C:/Project/GameOfLife/prj/project_microblaze/project_microblaze.runs/design_1_clk_wiz_1_0_synth_1/design_1_clk_wiz_1_0.dcp C:/Project/GameOfLife/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub C:/Project/GameOfLife/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub C:/Project/GameOfLife/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim C:/Project/GameOfLife/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim C:/Project/GameOfLife/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir C:/Project/GameOfLife/prj/project_microblaze/project_microblaze.ip_user_files/ip/design_1_clk_wiz_1_0]} {
  catch { 
    file copy -force C:/Project/GameOfLife/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_stub.v C:/Project/GameOfLife/prj/project_microblaze/project_microblaze.ip_user_files/ip/design_1_clk_wiz_1_0
  }
}

if {[file isdir C:/Project/GameOfLife/prj/project_microblaze/project_microblaze.ip_user_files/ip/design_1_clk_wiz_1_0]} {
  catch { 
    file copy -force C:/Project/GameOfLife/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_stub.vhdl C:/Project/GameOfLife/prj/project_microblaze/project_microblaze.ip_user_files/ip/design_1_clk_wiz_1_0
  }
}
