set_property SRC_FILE_INFO {cfile:C:/Project/GameOfLife/constraints/pins.xdc rfile:../../../../../constraints/pins.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W12 IOSTANDARD LVCMOS33} [get_ports ce]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVCMOS33} [get_ports shift]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB9 IOSTANDARD LVCMOS33} [get_ports Q]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_macro cell0
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
update_macro [get_macros cell0] -rlocs {FDRE_I1 X55Y49 LUT6_BIT0 X55Y49 LUT6_BIT1 X55Y49 CARRY4_obj X55Y49 LUT6_LAST_BIT1 X55Y49 LUT6_BIT2 X55Y49}
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells FDRE_I1]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X55Y49 [get_cells FDRE_I1]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells LUT6_BIT1]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X55Y49 [get_cells LUT6_BIT1]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL CARRY4 [get_cells CARRY4_obj]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X55Y49 [get_cells CARRY4_obj]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells LUT6_LAST_BIT1]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X55Y49 [get_cells LUT6_LAST_BIT1]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells LUT6_BIT2]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X55Y49 [get_cells LUT6_BIT2]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells LUT6_BIT0]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X55Y49 [get_cells LUT6_BIT0]
