# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Project/GameOfLife/prj/project_cell/project_cell.cache/wt [current_project]
set_property parent.project_path C:/Project/GameOfLife/prj/project_cell/project_cell.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/Project/GameOfLife/prj/project_cell/project_cell.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Project/GameOfLife/prj/project_cell/project_cell.srcs/sources_1/new/cell.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Project/GameOfLife/constraints/pins.xdc
set_property used_in_implementation false [get_files C:/Project/GameOfLife/constraints/pins.xdc]


synth_design -top cell -part xc7z020clg484-1


write_checkpoint -force -noxdef cell.dcp

catch { report_utilization -file cell_utilization_synth.rpt -pb cell_utilization_synth.pb }
