set_property BEL CARRY4 [get_cells CARRY4_obj]
set_property LOC SLICE_X43Y54 [get_cells CARRY4_obj]
set_property BEL AFF [get_cells FDRE_I1]
set_property LOC SLICE_X43Y54 [get_cells FDRE_I1]
set_property BEL B6LUT [get_cells g0_b0]
set_property LOC SLICE_X43Y54 [get_cells g0_b0]
set_property BEL C6LUT [get_cells g0_b1]
set_property LOC SLICE_X43Y54 [get_cells g0_b1]
set_property BEL D6LUT [get_cells g0_b2]
set_property LOC SLICE_X43Y54 [get_cells g0_b2]
set_property LOC SLICE_X43Y54 [get_cells LUT6_LAST/LUT5]
set_property LOC SLICE_X43Y54 [get_cells LUT6_LAST/LUT6]


set_property BEL A6LUT [get_cells LUT6_LAST]
set_property LOC SLICE_X43Y54 [get_cells LUT6_LAST]
